/* DB 접근 계정 생성 및 권한 설정 */
--


/*테이블 삭제
DROP TABLE MEMBER;
DROP TABLE ORDER2;
DROP TABEL NEWORDER2;
DROP TABLE CART;
DROP TABLE BOOKCOVER;
DROP TABLE BOOK;
DROP TABLE QNA;
DROP TABLE NOTICE;
DROP TABLE EVENT;
DROP TABLE WITHDRAW;
*/

--1. 사용자 테이블
CREATE TABLE MEMBER (
    MID VARCHAR2(30),
    MNO NUMBER(5) ,
    MPW VARCHAR2(20) NOT NULL,
    MNAME  VARCHAR2(20)         NOT NULL ,
    MEMAIL     VARCHAR2(50)     NOT NULL ,
    MPHONE     VARCHAR2(20)     NOT NULL ,
    MZIP_CODE              VARCHAR2(10)  ,
    M_FIRST_ADDR           VARCHAR2(120) ,
    M_SECOND_ADDR          VARCHAR2(90)  ,
    MDATE         DATE        ,  
    MBIRTHDAY  NUMBER(8)      ,   
    MGENDER    VARCHAR2(1)     ,
    AUTHORITY  NUMBER(1)      NOT NULL,

   CONSTRAINT PK_MEMBER PRIMARY KEY (MID),
);
COMMENT ON TABLE MEMBER IS '회원 테이블';
COMMENT ON TABLE MEMBER.MID IS '아이디';
COMMENT ON TABLE MEMBER.MPW IS '비밀번호';
COMMENT ON TABLE MEMBER.MNAME IS '이름';
COMMENT ON TABLE MEMBER.MEMAIL IS '이메일';
COMMENT ON TABLE MEMBER.MPHONE IS '휴대폰번호';
COMMENT ON TABLE MEMBER.MZIP_CODE IS '우편번호';
COMMENT ON TABLE MEMBER.M_FIRST_ADDR IS '도로명주소';
COMMENT ON TABLE MEMBER.M_SECOND_ADDR IS '상세주소';
COMMENT ON TABLE MEMBER.MDATE IS '회원가입일';
COMMENT ON TABLE MEMBER.MBIRTHDAY IS '생년월일';
COMMENT ON TABLE MEMBER.MGENDER IS '성별';
COMMENT ON TABLE MEMBER.AUTHORITY IS '권한';

----MEMBER PL/SQL문. 
SET SERVEROUTPUT ON;
DECLARE
I NUMBER := 1; --시작번호
BEGIN
LOOP
INSERT INTO MEMBER VALUES(MB_SEQ.NEXTVAL, I, '12345', '이림', 'LIM111@NAVER.COM', '01012345678', '00900', '서울시 강북구', '인수동', DEFAULT, 2, 19940422, 0);
I := I+1; -- 증가수이
EXIT WHEN I>201; --끝번호
END LOOP;

END;
/


--2. 주문 테이블
CREATE TABLE ORDER2(
ONO NUMBER(20) PRIMARY KEY,
MID VARCHAR2(30),
ODATE DATE DEFAULT SYSDATE,
ODPRICE NUMBER(4),
OTOTALPRICE NUMBER(10),
OSALESPRICE NUMBER(10),
ONAME VARCHAR2(20),
OPHONE VARCHAR2(20),
OADDR1 VARCHAR2(10),
OADDR2 VARCHAR2(120),
OADDR3 VARCHAR2(90),
OMEMO VARCHAR2(100),
OPAY VARCHAR2(30),
OTOTALAMOUNT NUMBER(4),
OSTATUS VARCHAR2(20),
CONSTRAINT ORDER_FK FOREIGN KEY (MID) REFERENCES MEMBER(MID)
);

COMMENT ON TABLE ORDER2 IS '주문 테이블';
COMMENT ON TABLE ORDER2.ONO IS '주문번호';
COMMENT ON TABLE ORDER2.MID IS '아이디';
COMMENT ON TABLE ORDER2.ODATE IS '주문일자';
COMMENT ON TABLE ORDER2.ODPRICE IS '배송비';
COMMENT ON TABLE ORDER2.OTOTALPRICE IS '총 가격';
COMMENT ON TABLE ORDER2.OSALESPRICE IS '총 할인 후 가격';
COMMENT ON TABLE ORDER2.ONAME IS '수령인';
COMMENT ON TABLE ORDER2.OPHONE IS '수령인 연락처';
COMMENT ON TABLE ORDER2.OADDR1 IS '우편번호';
COMMENT ON TABLE ORDER2.OADDR2 IS '시군구 주소';
COMMENT ON TABLE ORDER2.OADDR3 IS '상세주소';
COMMENT ON TABLE ORDER2.OMEMO IS '배송메모';
COMMENT ON TABLE ORDER2.OPAY IS '결제수단';
COMMENT ON TABLE ORDER2.OTOTALAMOUNT IS '총 책수량';
COMMENT ON TABLE ORDER2.OSTATUS IS '주문상태';

----ONO 시퀀스 생성
CREATE SEQUENCE ono_se INCREMENT BY 1 START WITH 1;


--3. 새로운 주문 테이블
CREATE TABLE NEWORDER2 (	
ONO NUMBER(20) NOT NULL,
DNO NUMBER(15),
BISBN VARCHAR2(100) NOT NULL,
OAMOUNT NUMBER(3) NOT NULL,
CONSTRAINT A1 FOREIGN KEY(ONO) REFERENCES ORDER2(ONO),
CONSTRAINT A2 FOREIGN KEY(DNO) REFERENCES BOOKCOVER(DNO),
CONSTRAINT A3 FOREIGN KEY(BISBN) REFERENCES BOOK(BISBN)
);

COMMENT ON TABLE NEWORDER2 IS '새로운 주문 테이블';
COMMENT ON TABLE NEWORDER2.ONO IS '주문번호';
COMMENT ON TABLE NEWORDER2.DNO IS '북커버번호';
COMMENT ON TABLE NEWORDER2.BISBN IS '책번호';
COMMENT ON TABLE NEWORDER2.OAMOUNT IS '책 수량';


--4.장바구니 테이블
CREATE TABLE CART(
CNO NUMBER(4) PRIMARY KEY,
MID VARCHAR2(30),
DNO NUMBER(15),
BISBN VARCHAR2(100),
OAMOUNT NUMBER(4),
CONSTRAINT FK_CART_MID FOREIGN KEY (MID) REFERENCES MEMBER(MID),
CONSTRAINT FK_CART_DNO FOREIGN KEY (DNO) REFERENCES BOOKCOVER(DNO),
CONSTRAINT FK_CART_BISBN FOREIGN KEY (BISBN) REFERENCES BOOK(BISBN)
);

COMMENT ON TABLE CART IS '장바구니 테이블';
COMMENT ON TABLE CART.CNO IS '장바구니번호';
COMMENT ON TABLE CART.MID IS '아이디';
COMMENT ON TABLE CART.DNO IS '북커버번호';
COMMENT ON TABLE CART.BISBN IS '책번호';
COMMENT ON TABLE CART.OAMOUNT IS '책수량';

----CNO 시퀀스 생성
CREATE SEQUENCE cno_se INCREMENT BY 1 START WITH 1;


--5.북커버 테이블
CREATE TABLE BOOKCOVER(
    DNO NUMBER(15) PRIMARY KEY,
    MID VARCHAR2(30),
    DDESC VARCHAR2(20),
    DIMG LONG,
    DPRICE NUMBER(4)
);


COMMENT ON TABLE BOOKCOVER IS '북커버 테이블';
COMMENT ON TABLE BOOKCOVER.DNO IS '북커버번호';
COMMENT ON TABLE BOOKCOVER.MID IS '아이디';
COMMENT ON TABLE BOOKCOVER.DDESC IS '북커버정보';
COMMENT ON TABLE BOOKCOVER.DIMG IS '북커버이미지';
COMMENT ON TABLE BOOKCOVER.DPRICE IS '북커버가격';

---- BOOKCOVER INSERT 
insert into bookcover values(0, 0, 0, 0, 0);


--6.책 테이블
CREATE TABLE BOOK (
    BISBN VARCHAR2(100),
    BCATEGORYID VARCHAR2(30) NOT NULL,
    BTITLE VARCHAR2(500) NOT NULL,
    BAUTHOR VARCHAR2(500) NOT NULL,
    BDISCRIPTION VARCHAR2(1800),
    BCOVER VARCHAR2(300),
    BPRICESTANDARD NUMBER(20),
    BPRICESALES NUMBER(20),
    BPUBLISHER VARCHAR2(100),
    BPUBDATE VARCHAR2(100),
    BSTOCK NUMBER,
    BBEST VARCHAR2(10),
    BBLOG VARCHAR(10),
    BNEW VARCHAR2(10),
    BCATEGORY VARCHAR2(10)
);


COMMENT ON TABLE BOOK IS '책 테이블';
COMMENT ON TABLE BOOK.BISBN IS '책 번호';
COMMENT ON TABLE BOOK.BCATEGORYID IS '책 카테고리번호';
COMMENT ON TABLE BOOK.BTITLE IS '책 제목';
COMMENT ON TABLE BOOK.BAUTHOR IS '책 저자';
COMMENT ON TABLE BOOK.BDISCRIPTION IS '책 소개';
COMMENT ON TABLE BOOK.BCOVER IS '책 표지';
COMMENT ON TABLE BOOK.BPRICESTANDARD IS '책 표준가격';
COMMENT ON TABLE BOOK.BPRICESALES IS '책 세일가격';
COMMENT ON TABLE BOOK.BPUBLISHER IS '책 출판사';
COMMENT ON TABLE BOOK.BSTOCK IS '책 재고';
COMMENT ON TABLE BOOK.BBEST IS '베스트셀러';
COMMENT ON TABLE BOOK.BBLOG IS '블로그베스트셀러';
COMMENT ON TABLE BOOK.BNEW IS '신간도서';
COMMENT ON TABLE BOOK.BCATEGORY IS '소설';


--7.1대1문의 테이블
CREATE TABLE QNA (
    QNO NUMBER(10) PRIMARY KEY,
    MID VARCHAR2(30) NOT NULL,
    QTITLE VARCHAR2(120) NOT NULL,
    QDATE DATE DEFAULT SYSDATE,
    QCONTENT VARCHAR2(1800),
    QREF NUMBER(10) DEFAULT 1,
    QREF_STEP NUMBER(3) DEFAULT 1,
    QREF_LEVEL NUMBER(3) DEFAULT 1,
    QVIEW NUMBER,
    QTYPE VARCHAR2(30) DEFAULT '기타'
);


COMMENT ON TABLE QNA IS '1대1문의 테이블';
COMMENT ON TABLE QNA.QNO IS '1대1문의 글번호';
COMMENT ON TABLE QNA.MID IS '아이디';
COMMENT ON TABLE QNA.QTITLE IS '글제목';
COMMENT ON TABLE QNA.QDATE IS '작성일자';
COMMENT ON TABLE QNA.QCONTENT IS '글내용';
COMMENT ON TABLE QNA.QREF IS '글 그룹필드';
COMMENT ON TABLE QNA.QREF_STEP IS '글 스텝';
COMMENT ON TABLE QNA.QREF_LEVEL IS '글 레벨';
COMMENT ON TABLE QNA.QVIEW IS '조회수';
COMMENT ON TABLE QNA.QTYPE IS '글 유형';


----QNA PL/SQL 인서트
SET SERVEROUTPUT ON;
DECLARE
I NUMBER := 1;
BEGIN
LOOP
INSERT INTO QNA VALUES (I, 'SSAK', 'QREF_TITLE', SYSDATE, 'QREF_CONTEN', I, 1, 1, 0, DEFAULT);
I := I+1;
EXIT WHEN I>301;
END LOOP;

END;
/


--8.공지사항 테이블
CREATE TABLE NOTICE (
    NNO NUMBER(10) NOT NULL PRIMARY KEY,
    MID VARCHAR2(30) NOT NULL,
    NTITLE VARCHAR2(120) NOT NULL,
    NDATE DATE DEFAULT SYSDATE,
    NCONTENT VARCHAR2(4000) NOT NULL,
    NVIEW NUMBER DEFAULT 0,
    CONSTRAINT FK_NOTICE FOREIGN KEY (MID) REFERENCES MEMBER(MID)
);


COMMENT ON TABLE NOTICE IS '공지사항 테이블';
COMMENT ON TABLE NOTICE.NNO IS '공지사항 글번호';
COMMENT ON TABLE NOTICE.MID IS '아이디';
COMMENT ON TABLE NOTICE.NTITLE IS '글제목';
COMMENT ON TABLE NOTICE.NDATE IS '작성일자';
COMMENT ON TABLE NOTICE.NCONTENT IS '글내용';
COMMENT ON TABLE NOTICE.NVIEW IS '조회수';

----NOTICE SEQUENCE 생성
CREATE SEQUENCE NOTICE_SEQ 
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
NOCACHE;

----NOTICE PL/SQL 인서트
SET SERVEROUTPUT ON;
DECLARE
I NUMBER := 1;
BEGIN
LOOP
INSERT INTO NOTICE VALUES (I, 'SSAK', 'NOTICE_TITLE', SYSDATE, 'NOTICE_CONTENT', 0);
I := I+1;
EXIT WHEN I>301;
END LOOP;

END;
/


--9.이벤트 테이블
CREATE TABLE EVENT(
ENO NUMBER(10),
MID VARCHAR2(30),
ECONTENT VARCHAR(500),
EDATE DATE DEFAULT SYSDATE,
CONSTRAINT FK_EVENT FOREIGN KEY (MID) REFERENCES MEMBER(MID)
);


COMMENT ON TABLE EVENT IS '이벤트 테이블';
COMMENT ON TABLE EVENT.ENO IS '댓글번호';
COMMENT ON TABLE EVENT.MID IS '아이디';
COMMENT ON TABLE EVENT.ECONTENT IS '댓글내용';
COMMENT ON TABLE EVENT.EDATE IS '댓글 작성일자';


----EVENT 시퀀스 생성
CREATE SEQUENCE SEQ_ID INCREMENT BY 1 START WITH 1;


--10.탈퇴 테이블
CREATE TABLE WITHDRAW(
WNO  NUMBER(20) NOT NULL,
MID VARCHAR2(30) NOT NULL,
WRER VARCHAR2(1800) NOT NULL,
WRED DATE DEFAULT SYSDATE,
WACD CHAR(1) NOT NULL,
CONSTRAINT FOR_NAME FOREIGN KEY (MID) REFERENCES MEMBER(MID)
);


COMMENT ON TABLE WITHDRAW IS '탈퇴 테이블';
COMMENT ON TABLE WITHDRAW.WNO IS '탈퇴요청번호';
COMMENT ON TABLE WITHDRAW.MID IS '아이디';
COMMENT ON TABLE WITHDRAW.WRER IS '탈퇴사유';
COMMENT ON TABLE WITHDRAW.WRED IS '탈퇴요청일';
COMMENT ON TABLE WITHDRAW.WACD IS '탈퇴승인여부';

---- WITHDRAW 시퀀스 생성 
CREATE SEQUENCE WD_SEQ 
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE
NOCACHE;


----WITHDRAW PL/SQL(2가지) 
SET SERVEROUTPUT ON;
DECLARE
I NUMBER := 1;   --시작번호
BEGIN
LOOP
INSERT INTO WITHDRAW VALUES (WD_SEQ.NEXTVAL, I, 'AA', DEFAULT, 'Y');
I := I+1;   -- 증가수이
EXIT WHEN I>101;   --끝번호
END LOOP;
END;
/
DECLARE
I NUMBER := 101;   --시작번호
BEGIN
LOOP
INSERT INTO WITHDRAW VALUES (WD_SEQ.NEXTVAL, I, 'BB', DEFAULT, 'N');
I := I+1;   -- 증가수이
EXIT WHEN I>201;   --끝번호
END LOOP;
END;
/


